# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2d75f41b4915a3d60d8d6f287effafecdccf4c630015ddb3fe488513084ad078c4da677c0d3767454415d5c069bbabbb946928a21a403761944547f755e554

test:
  secret_key_base: 61a26b43b37981b58f7298a99edf6b70f886d4b1c6d1f18a6cce9718353e2783e632d19adf29e1933a26d3533addfcc24c0fec33e0bbe5111993188f1ddcc985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
